INSERT INTO state_codes (record_type, state_code, description)
VALUES
('S', 'AL', 'ALABAMA'),
('S', 'AK', 'ALASKA'),
('S', 'AZ', 'ARIZONA'),
('S', 'AR', 'ARKANSAS'),
('S', 'CA', 'CALIFORNIA'),
('S', 'CO', 'COLORADO'),
('S', 'CT', 'CONNECTICUT'),
('S', 'DE', 'DELAWARE'),
('S', 'FL', 'FLORIDA'),
('S', 'GA', 'GEORGIA'),
('S', 'HI', 'HAWAII'),
('S', 'ID', 'IDAHO'),
('S', 'IL', 'ILLINOIS'),
('S', 'IN', 'INDIANA'),
('S', 'IA', 'IOWA'),
('S', 'KS', 'KANSAS'),
('S', 'KY', 'KENTUCKY'),
('S', 'LA', 'LOUISIANA'),
('S', 'ME', 'MAINE'),
('S', 'MD', 'MARYLAND'),
('S', 'MA', 'MASSACHUSETTS'),
('S', 'MI', 'MICHIGAN'),
('S', 'MN', 'MINNESOTA'),
('S', 'MS', 'MISSISSIPPI'),
('S', 'MO', 'MISSOURI'),
('S', 'MT', 'MONTANA'),
('S', 'NE', 'NEBRASKA'),
('S', 'NV', 'NEVADA'),
('S', 'NH', 'NEW HAMPSHIRE'),
('S', 'NJ', 'NEW JERSEY'),
('S', 'NM', 'NEW MEXICO'),
('S', 'NY', 'NEW YORK'),
('S', 'NC', 'NORTH CAROLINA'),
('S', 'ND', 'NORTH DAKOTA'),
('S', 'OH', 'OHIO'),
('S', 'OK', 'OKLAHOMA'),
('S', 'OR', 'OREGON'),
('S', 'PA', 'PENNSYLVANIA'),
('S', 'RI', 'RHODE ISLAND'),
('S', 'SC', 'SOUTH CAROLINA'),
('S', 'SD', 'SOUTH DAKOTA'),
('S', 'TN', 'TENNESSEE'),
('S', 'TX', 'TEXAS'),
('S', 'UT', 'UTAH'),
('S', 'VT', 'VERMONT'),
('S', 'VA', 'VIRGINIA'),
('S', 'WA', 'WASHINGTON'),
('S', 'DC', 'WASHINGTON, D.C.'),
('S', 'WV', 'WEST VIRGINIA'),
('S', 'WI', 'WISCONSIN'),
('S', 'WY', 'WYOMING'),
('S', 'AP', 'ARMED FORCES PACIFIC'),
('S', 'AE', 'ARMED FORCES EUROPE'),
('S', 'AA', 'ARMED FORCES AMERICA');